name: Environment Variables

on:
  push:
    branches:
      - development
      - production

jobs:
  build:
    runs-on: self-hosted
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/production' && 'production' || 'development' }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Deploy to environment
        run: dep deploy ${{ env.ENVIRONMENT }}
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          DEPLOYER_HOST: ${{ secrets.ENVIRONMENT == 'production' && secrets.PRODUCTION_HOST || secrets.STAGING_HOST }}
          DEPLOYER_USER: ${{ secrets.ENVIRONMENT == 'production' && secrets.PRODUCTION_USER || secrets.STAGING_USER }}